### ISSUE TITLE
rangerSaga.ts

### ISSUE THREAD

**Issue by HafeezRai** [openware/baseapp#12]
I am getting this error 
(171,13): Type 'Channel<unknown>' is not assignable to type 'Channel<{}>'.
  Type 'unknown' is not assignable to type '{}'.

anyone have same issue?

**Comment by calj** [comment]
I noticed this problem but it was not a blocker.
Does it prevent you to build the application?

**Comment by HafeezRai** [comment]
yes first it prevent from build application and second if i change Channel<{}> to Channel<unknown> than it build but does not connect to ranger

**Comment by akhlopiachyi** [comment]
Hello @HafeezRai 
Do you still have this issue?
