### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by cleardex** [openware/baseapp#126]
Following the updates of OpenDax on March 27 2020, this frontend no longer works and instead results in a blank page.

**Comment by mikoim** [comment]
Try to disable JavaScript Obfuscator.
https://github.com/openware/baseapp/blob/4cb1f34465cb9e4e93c511e9bb9f6c3932a566af/config-overrides.js#L31-L33

**Comment by cleardex** [comment]
Thank you this has brought up the correct page again. However, there is one small error "Route is not found 404". Any idea what is causing this?
Again thanks for your help.

**Comment by mikoim** [comment]
@cleardex When enabling SSL encryption after deploy, I stuck a similar issue because envoy settings were not applied. To ensure applying configuration, restart all containers.

**Comment by cleardex** [comment]
> @cleardex When enabling SSL encryption after deploy, I stuck a similar issue because envoy settings were not applied. To ensure applying configuration, restart all containers.

Thanks for the feedback with this. I had already restarted all the containers but unfortunately, this did not resolve it for me.

**Comment by cleardex** [comment]
Has anyone found a solution to this issue? Restarting all the docker containers did not solve it. Thanks in advance.

**Comment by mikoim** [comment]
@cleardex Could you provide ``docker-compose logs``?

**Comment by Shreybhardwaj97** [comment]
> Try disabling JavaScript Obfuscator.
> 
> https://github.com/openware/baseapp/blob/4cb1f34465cb9e4e93c511e9bb9f6c3932a566af/config-overrides.js#L31-L33

Do we need to comment out and restart the rake services?

**Comment by Shreybhardwaj97** [comment]
I'm getting an error that 
data is not defined
    _0xbf0cb3 https://exchange.com/static/js/main.01b29bfe.js:1
    _0x49d239 https://exchange.com/static/js/main.01b29bfe.js:1
    _0x4c0647 https://exchange.com/static/js/main.01b29bfe.js:1
    <anonymous> https://exchange.com/static/js/main.01b29bfe.js:1
    <anonymous> https://exchange.com/static/js/main.01b29bfe.js:1

**Comment by mikoim** [comment]
@Shreybhardwaj97 Yes
comment out -> ``docker build .`` -> update app.yaml -> ``rake render:config`` -> ``docker-compose restart frontend``

**Comment by Shreybhardwaj97** [comment]
@mikoim thank-you it works :) only there are few error route errors

**Comment by ruby261** [comment]
@Shreybhardwaj97 
Can you please tell me how did you disable 
 config.plugins.push( 
     new JavaScriptObfuscator({ rotateUnicodeArray: true, domainLock: domain }, [commonJSFilename]) 
 ); 

or did you comment those three-line ?

**Comment by Shreybhardwaj97** [comment]
@ruby261 kindly comment this one

    config.plugins.push(
          //  new JavaScriptObfuscator({ rotateUnicodeArray: true, domainLock: domain }, //[commonJSFilename])
 //       );

and then run the code
