### ISSUE TITLE
Style sheets

### ISSUE THREAD

**Issue by cleardex** [openware/baseapp#129]
Hello,
Im trying to find the styles sheet to manipulate the font and size and images for the following items:

e.g. page.body.landing.features.features.item1.title in src/translations/en.ts

I have been unable to find the relevant file. Is there any documentation for this? If not can someone who has done this before perhaps point me in the right direction? Thanks.

**Comment by cleardex** [comment]
Found images: /src/assets/images/landing/features
However still not sure where the text style for the font size is located.

**Comment by ruby261** [comment]
@cleardex did you fix 404 route not found error ?

**Comment by marquis-ogre** [comment]
@cleardex The Text Font Styles are here : https://github.com/openware/baseapp/blob/master/src/index.pcss#L6
https://github.com/openware/baseapp/blob/master/src/screens/History/HistoryTab.pcss#L97
https://github.com/openware/baseapp/blob/master/src/screens/OrdersTabScreen/OrdersTabScreen.pcss#L87
https://github.com/openware/baseapp/blob/master/src/screens/WalletsScreen/WalletsScreen.pcss#L548
