### ISSUE TITLE
Frontend not showing up

### ISSUE THREAD

**Issue by behnammby** [openware/baseapp#178]
Installing a fresh new opendax on Debian 9, ruby 2.6.5.

installing docker and docker-compose
installing ruby rvm
clone opendax
install bundler
bundle install
rake service:all[start]

and all services are up, no error

but when opening frontend in browser by typing the domain configured in config/app.yaml, I see the following error in the console and nothing is displayed but a blank page with gray background.

main.d2e6ef35.js:1 Uncaught ReferenceError: data is not defined
    at main.d2e6ef35.js:1
    at _0x50e05e (main.d2e6ef35.js:1)
    at _0x474aea (main.d2e6ef35.js:1)
    at main.d2e6ef35.js:1
    at main.d2e6ef35.js:1

**Comment by akhlopiachyi** [comment]
Issue is related not to frontend
Please, specify the issue for Opendax
