### ISSUE TITLE
Landing page always routes to trading page

### ISSUE THREAD

**Issue by leocape** [openware/baseapp#197]
(Master)

The landing page automatically routes to the trading page regardless of the config set in env.js

Temporary workaround:

baseapp/src/routes/Layout/index.tsx

- Revert  (Line 193) ` {showLanding() && <Route exact={true} path="/" component={LandingScreen} />}` back to `<Route exact={true} path="/" component={LandingScreen} /> `

**Comment by cryptoruby** [comment]
@leocape Hi Dear, can you share your baseapp/src/routes/Layout/index.tsx file ?
did you remove line 193 ?

**Comment by IbrahimSerhat** [comment]
Hi,
i have same issue.

if i start all services on localhost, its running perfectly. but on hosting, page was empty and i fix it with that
https://github.com/openware/opendax/issues/157#issuecomment-641498171

landing page always routes to trading page after that.

**Comment by akhlopiachyi** [comment]
@leocape Can you share your env.js if you still can represent the issue?
