### ISSUE TITLE
PM2 for run baseapp production

### ISSUE THREAD

**Issue by UbuntuEvangelist** [openware/baseapp#21]
is their any app.js or others file thus it can use for PM2 for run baseapp production?
https://pm2.keymetrics.io/

**Comment by calj** [comment]
I'm afraid not, this is a frontend application.
The build output static files.

**Comment by UbuntuEvangelist** [comment]
how to run this production?

**Comment by UbuntuEvangelist** [comment]
any way to run baseapp into production build as standalone?
