### ISSUE TITLE
Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`>

### ISSUE THREAD

**Issue by venkateshsys** [openware/baseapp#333]
All the docker containers are running fine, but when I hit the URL which I have defined in app.yml file, it shows the error like this on black-white page `An unhandled lowlevel error occurred. The application logs may have details.`

![image](https://user-images.githubusercontent.com/48546261/94347579-19cbbc00-0053-11eb-90d7-3fdd41fffd69.png)

these are the logs inside the frontend docker container
![image](https://user-images.githubusercontent.com/48546261/94347601-48499700-0053-11eb-8b4c-05a367b972d5.png)

**Comment by akhlopiachyi** [comment]
@venkateshsys Your error isn't related to base app project (https://github.com/openware/baseapp)
If you are using opendax, report the issue there
