### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by eliudrojas** [openware/baseapp#344]
Hi
I'm running baseapp 2.4.0 and opendax and everything it's ok, but I can see that app throws an errror

wss://domain.com/api/v2/rango/private/?stream=deposit_address&stream=ethusdt.ob-inc&stream=ethusdt.trades&stream=global.tickers&stream=order&stream=trade
401 UNAUTHORIZED 

I'm trying to figure out what happends, but I can't find the error

I can sign in ok and when I'm signin, baseapp throws me this error

Any advice to resolve this problem? 

----

  peatio: quay.io/openware/peatio:2.4.19
  barong: quay.io/openware/barong:2.4.12
  frontend: custom/frontend:2.4.0
  tower: quay.io/openware/tower:2.4.9
  rango: custom/rango:2.4.0

Thanks

**Comment by akhlopiachyi** [comment]
@eliudrojas Use ranger instead of rango

**Comment by eliudrojas** [comment]
ok I will try it

Thanks !!!
