### ISSUE TITLE
error in yarn start-mock

### ISSUE THREAD

**Issue by kroim** [openware/baseapp#382]
Baseapp is not running ... 
![image](https://user-images.githubusercontent.com/33049672/98884225-8c411000-24ca-11eb-9006-32ac74d868a8.png)

**Comment by kroim** [comment]
![image](https://user-images.githubusercontent.com/33049672/98886349-db893f80-24ce-11eb-8ed9-149cafdb8837.png)

**Comment by josadcha** [comment]
Hello @kroim !
Thanks for using baseapp.

Such issue appear when mockserver is already running on port 9002, please check if other tabs on your terminal are not running yarn start-mock command of baseapp.

**Comment by kroim** [comment]
Another mock server is not working on local. I think that it is tried on a Windows system. 
It works on a Linux system as well.
Thanks for your everything.
