### ISSUE TITLE
Uncaught (in promise) TypeError: e._innerWindow(...).widgetReady is not a function

### ISSUE THREAD

**Issue by crackfoo** [openware/baseapp#458]
I've seen this issue in TradingView github and several posts have indicated to serve build without -s but seems that made no improvement...

I'm using 2.5.5 of baseapp and wondering if anyone has had this problem? It throws this error when I load the trading page and affects just the chart when you change markets. Everything else changes to the proper market except the chart doesn't switch...

![image](https://user-images.githubusercontent.com/6303714/107099346-d0049680-67e7-11eb-987f-ed31094296fd.png)

Thanks

**Comment by crackfoo** [comment]
Reference to issue from tradingview: https://github.com/tradingview/charting-library-examples/issues/15#issuecomment-411001758

**Comment by crackfoo** [comment]
But alas, I do see it's set in here:

https://github.com/openware/baseapp/blob/master/src/containers/TradingChart/config.ts#L29

Not sure what else to do to figure this. Has no one else seen this issue? I get it right out of the box 2.6 and 2.5 and is about the last thing that's not working

**Comment by kodlar** [comment]
Check your "TradingView.version" from console mine is 1.14
console output
ƒ s() { return "1.14 (internal id aaac22e2 @ 2019-04-04 08:31:56.077488)" }

I got the same error, on my local windows 10 machine but unfortunately on production server which is ubuntu it works well
my library path is correct and I decide to change my local settings from my local language to english
from locale: "tr", to locale: "en", it works.

**Comment by crackfoo** [comment]
thanks for the suggestion.

I have s(){return"1.15 (internal id 8562c7b8 @ 2019-12-18 11:58:08.555993) and now using baseapp 2.6.14 and still throws this error... and I've had everything else as default which was en....

**Comment by crackfoo** [comment]
This issue was caused by CloudFlare's "Rocket Loader" 

Disabled it and the charting now works as expected.

**Comment by bitcointryExchange** [comment]
> This issue was caused by CloudFlare's "Rocket Loader"
> 
> Disabled it and the charting now works as expected.


Problem solved. Cloudflare Rocket Loader is the source of this problem. I turned it off and the problem went away.
Thank you.
