### ISSUE TITLE
How to let user deposit and withdraw only after Email address verification?

### ISSUE THREAD

**Issue by sguides28** [openware/baseapp#473]
I want users to be able to deposit and withdraw after level 1 - Email verification.
![image](https://user-images.githubusercontent.com/79210354/108224371-8438e200-7143-11eb-8138-a5b638e1b781.png)

**Comment by crackfoo** [comment]
Set it here:

https://github.com/openware/opendax/blob/2-5-stable/templates/config/peatio.env.erb#L41

**Comment by sguides28** [comment]
> Set it here:
> 
> https://github.com/openware/opendax/blob/2-5-stable/templates/config/peatio.env.erb#L41

Thank you so much!
