### ISSUE TITLE
Edit css file in baseapp

### ISSUE THREAD

**Issue by saeedjaafari** [openware/baseapp#479]
hi guys
1- in the project where is the main css file to edit ? forexample to change the style to rtl
2- where is the html file ? i wanna change some text but i dont find the html source

thanks for guide
Alex

**Comment by akushniruk** [comment]
Hello @saeedjaafari

1. Right now baseapp used postcss and to edit the styles u need to look into /web/src/index.pcss. For changing style to rtl i can recommend u try to use webpack plugins.
2. Path to the html file web/src/app/template.html. In this file, u can find id="root" to which we connecting ReactJS. But for changing any screens/containers/components better to start a local server.
**Readme:** https://github.com/openware/baseapp/blob/master/web/README.md.

For changing text u need to edit: web/src/translations/en.ts
