### ISSUE TITLE
2.6 getting error WEBPACK_IMPORTED_MODULE_12__.colors[colorTheme] is undefined

### ISSUE THREAD

**Issue by cryptonana** [openware/baseapp#493]
i run yarn install and after run  
`yarn start-mock`

and try to open in browser i see this error please someone help me

TypeError: _constants__WEBPACK_IMPORTED_MODULE_12__.colors[colorTheme] is undefined
OrderBookContainer/_this.orderBook
src/containers/OrderBook/index.tsx:138

  135 | maxVolume={calcMaxVolume(bids, asks)}
  136 | orderBookEntryAsks={accumulateVolume(asks)}
  137 | orderBookEntryBids={accumulateVolume(bids)}
> 138 | rowBackgroundColorAsks={colors[colorTheme].orderBook.asks}
      | ^  139 | rowBackgroundColorBids={colors[colorTheme].orderBook.bids}
  140 | dataAsks={this.renderOrderBook(asksData, 'asks', this.props.intl.formatMessage({id: 'page.noDataToShow'}), currentMarket)}
  141 | dataBids={this.renderOrderBook(bids, 'bids', this.props.intl.formatMessage({id: 'page.noDataToShow'}), currentMarket)}

render
src/containers/OrderBook/index.tsx:118

  115 |             <div className={'cr-table-header__content'}>
  116 |                 {this.props.intl.formatMessage({id: 'page.body.trade.orderbook'})}
  117 |             </div>
> 118 |             {orderBookLoading ? <div className="pg-combined-order-book-loader"><Spinner animation="border" variant="primary" /></div> : this.orderBook(bids, asks)}
      | ^  119 |         </div>
  120 |     );
  121 | }

**Comment by oyershov** [comment]
Hello, you need to clear the cache.
Probably you used previous version of the baseApp where `dark` theme had name `basic`, so the browser cashed it.
