### ISSUE TITLE
Unable to compile because of github.com/openware/sonic

### ISSUE THREAD

**Issue by kde99** [openware/baseapp#517]
Trying to run "docker build" fails with  "github.com/openware/sonic invalid version: unknown revision 2c220ea19081" going to their page you can indeed confirm that commit with id 2c220ea19081 doesn't exist. (What's worse is that they even have link to this non existing commit in skel/go.mod)

**Comment by medjessy** [comment]
+1 I am having the same problem.

**Comment by akushniruk** [comment]
Hello, @medjessy  @kde99  
Thank you for notifying us, we really have a problem with this, and team already prepared a fix. 
https://github.com/openware/baseapp/pull/508
We will merge it soon. 
For a better experience, I can recommend for you to use stable versions.
