### ISSUE TITLE
New Baseapp (master) does not support postgresql even though opendax supports it

### ISSUE THREAD

**Issue by ianeinser** [openware/baseapp#831]
Hi,

I suppose baseapp has not supported postgresql yet

[Kaigara] 2021/10/18 02:02:06 KAIGARA_REDIS_URL unset, do not connect to redis
[Kaigara] 2021/10/18 02:02:06 Starting command: ./bin/sonic [serve]
[Kaigara] 2021/10/18 02:02:06 Publishing on log.sonic.stdout and log.sonic.stderr
[Kaigara] 2021/10/18 02:02:06 Reached EOF on STDIN
[mysql] 2021/10/18 02:03:06 packets.go:36: unexpected EOF
[mysql] 2021/10/18 02:04:06 packets.go:36: unexpected EOF
[mysql] 2021/10/18 02:05:06 packets.go:36: unexpected EOF
2021/10/18 02:05:06 driver: bad connection

2021/10/18 02:05:06 /go/pkg/mod/github.com/openware/pkg/database@v0.0.0-20210113145702-fb5cceb8f775/database.go:37
[error] failed to initialize database, got error driver: bad connection
[Kaigara] 2021/10/18 02:05:06 exit status 1

I use postgres but baseapp displays only mysql

**Comment by akhlopiachyi** [comment]
Hello @ianeinser 
This issue is not related to the baseapp so I close it
Please create issue in Peatio or Barong repos
