### ISSUE TITLE
authz.invalid_session error when accessing admin

### ISSUE THREAD

**Issue by LunaXOXO** [openware/baseapp#832]
I'm getting the following 401 response when accessing /admin/ on a fresh opendax install
`{"errors":["authz.invalid_session"]}`
This is before entering any credentials and happens whether or not i'm signed into the baseapp frontend using the default admin user or not signed in at all.
What's causing this issue or how do i debug it, I'm new to OpenDAX so still learning. I'm running on an ubuntu server 20.04 virtual machine.

**Comment by akhlopiachyi** [comment]
Hello @LunaXOXO 
This issue is not related to the baseapp so I close it
Please create issue in Peatio or Barong repos
