### ISSUE TITLE
Docker Build Error!

### ISSUE THREAD

**Issue by bleachhun** [openware/baseapp#833]
[3/5] Linking dependencies...
warning " > @capacitor/android@2.4.1" has incorrect peer dependency "@capacitor/core@~2.4.0".
warning " > @capacitor/ios@2.4.1" has incorrect peer dependency "@capacitor/core@~2.4.0".
warning " > @typescript-eslint/eslint-plugin@3.10.1" has incorrect peer dependency "@typescript-eslint/parser@^3.0.0".
warning " > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
warning " > react-dom@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning " > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
warning "react-intl > @formatjs/intl@1.14.1" has incorrect peer dependency "@types/node@14 || 16".
warning " > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning nohoist config is ignored in "@openware/cryptofont" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
warning Workspaces can only be enabled in private projects.

**Comment by whatnowangga** [comment]
Got a same issue here
