### ISSUE TITLE
Remove mockserver reference from readme

### ISSUE THREAD

**Issue by 3DA4C300** [openware/baseapp#84]
https://github.com/openware/mockserver repository seems to be no longer available, please remove it from readme

**Comment by bitcoinsfacil** [comment]
You can find it on https://github.com/rubykube/mockserver @3DA4C300 
Some values will be missing from api but it is a great local development solution.

**Comment by akhlopiachyi** [comment]
@bitcoinsfacil @3DA4C300 Right now mockserver is available from baseapp, but still some values could be missing
You can find all mocked files here `https://github.com/openware/baseapp/tree/master/mocks`
If you want to use it, run ```yarn start-mock```
