### ISSUE TITLE
About .../src/helpers/layout.ts

### ISSUE THREAD

**Issue by doodar87** [openware/baseapp#88]
Hi, am teaching baseapp project and i have a question) is there an easier way to set the order of components than setting coordinates in .../src/helpers/layout.ts, I mean, can I somehow get the configuration after drag and drop or another way? Thank you in advance for your response.

**Comment by akhlopiachyi** [comment]
You can write static configs for layout

The script, what is written in `src/helpers/layout.ts` created for dynamical update of trading screen's grid items, their layout depends on user's screen size
