### ISSUE TITLE
warning : unmet peer dependency

### ISSUE THREAD

**Issue by ruby261** [openware/baseapp#96]
how to fix these warnings

```
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
warning " > react-fade-in@0.1.6" has incorrect peer dependency "react@^15.4.1".
warning " > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
warning " > react-intl@2.9.0" has unmet peer dependency "prop-types@^15.5.4".
warning " > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > react-app-rewired@1.6.2" has incorrect peer dependency "react-scripts@^1.0.14".
warning " > ts-jest@23.10.5" has incorrect peer dependency "jest@>=22 <24".
warning nohoist config is ignored in "@openware/cryptofont" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
```

**Comment by jobinpankajan** [comment]
> how to fix these warnings
> 
> ```
> warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
> warning " > bootstrap@4.4.1" has unmet peer dependency "popper.js@^1.16.0".
> warning " > react-fade-in@0.1.6" has incorrect peer dependency "react@^15.4.1".
> warning " > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
> warning " > react-intl@2.9.0" has unmet peer dependency "prop-types@^15.5.4".
> warning " > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > react-app-rewired@1.6.2" has incorrect peer dependency "react-scripts@^1.0.14".
> warning " > ts-jest@23.10.5" has incorrect peer dependency "jest@>=22 <24".
> warning nohoist config is ignored in "@openware/cryptofont" because it is not a private package. If you think nohoist should be allowed in public packages, please submit an issue for your use case.
> ```

**How did you solve this issue ?**
