### ISSUE TITLE
route not found 404

### ISSUE THREAD

**Issue by ruby261** [openware/baseapp#98]
I am getting this error

` Route not found 404`

can anyone help me, how can i fix it.

**Comment by akhlopiachyi** [comment]
@ruby261 Hello
How did you get this error?
Can you specify more description?

**Comment by ruby261** [comment]
@akhlopiachyi once i compile baseapp with

`docker build -t frontend/baseapp:2.0 .
`
And change opendax config/app.yml  

and run rake service:all 

i get error 

> Failed to load resource: the server responded with a status of 404 ()                /api/v2/barong/identity/configs:1

**Comment by akhlopiachyi** [comment]
@ruby261 Which version of opendax did you use?

**Comment by zeus-dev** [comment]
same error route 404 not found 
![Screenshot from 2020-03-14 18-52-07](https://user-images.githubusercontent.com/62093083/76682810-14fa6a00-6625-11ea-9306-2f47c6f2ebbd.png)

**Comment by akhlopiachyi** [comment]
@zeus-dev Seems you are using barong with version 2.3
Try to use the latest version

**Comment by enemy212326** [comment]
![Capture](https://user-images.githubusercontent.com/40855282/77908738-437b7480-72b6-11ea-86de-5879dbc41696.PNG)
  

Hi help me please

**Comment by ruby261** [comment]
@akhlopiachyi  Sorry for late reply. Which one should I use 
`https://quay.io/repository/openware/barong?tag=latest&tab=tags `

Can you point me in right direction
